import {
  Contact,
  Program,
  Enrollment,
  Reflection,
  LearningEvent,
  LearningSignal,
} from '@promotor/contracts';

export const SEED_ORGANIZATION = {
  id: 'org_stifin_parenting',
  name: 'STIFIn Parenting Indonesia',
  slug: 'rina',
  createdAt: '2026-01-01T00:00:00.000Z',
};

export const SEED_CONTACTS: Contact[] = [
  {
    id: 'contact_ayu',
    organizationId: SEED_ORGANIZATION.id,
    name: 'Ayu Lestari',
    phoneE164: '+6281987654321',
    createdAt: '2026-08-01T08:00:00.000Z',
  },
  {
    id: 'contact_budi',
    organizationId: SEED_ORGANIZATION.id,
    name: 'Budi Santoso',
    phoneE164: '+6281234567890',
    createdAt: '2026-08-02T09:30:00.000Z',
  },
  {
    id: 'contact_nina',
    organizationId: SEED_ORGANIZATION.id,
    name: 'Nina Rahmawati',
    phoneE164: '+6285678901234',
    createdAt: '2026-08-05T14:15:00.000Z',
  },
];

export const SEED_PROGRAMS: Program[] = [
  {
    id: 'prog_7_hari_belajar',
    organizationId: SEED_ORGANIZATION.id,
    workspaceSlug: 'rina',
    programSlug: '7-hari-mengenal-cara-belajar-anak',
    title: '7 Hari Mengenal Cara Belajar Anak',
    subtitle: 'Panduan Praktis Orang Tua Mengidentifikasi Mesin Kecerdasan Anak (STIFIn)',
    description: 'E-course 7 hari khusus untuk orang tua yang ingin memahami bakat genetik dan gaya belajar ideal anak.',
    programType: 'lead_magnet',
    accessType: 'public',
    status: 'published',
    pricing: 'free',
    priceAmount: 0,
    bankTransferEnabled: false,
    whatsAppEnabled: false,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
    modules: [
      {
        id: 'mod_1',
        programId: 'prog_7_hari_belajar',
        title: 'Modul 1: Mengenali Bakat Genetik Anak',
        order: 1,
        lessons: [
          {
            id: 'les_1_1',
            moduleId: 'mod_1',
            title: 'Sesi 1: Mengapa Setiap Anak Unik?',
            order: 1,
            videoYoutubeUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
            videoExternalId: 'dQw4w9WgXcQ',
            textContent: 'Pola belajar anak sangat dipengaruhi oleh mesin kecerdasan dominan yang dibawanya sejak lahir.',
            hasReflection: true,
            reflectionType: 'long_text',
            reflectionPrompt: 'Tuliskan pengamatan Anda tentang kebiasaan belajar anak yang paling menonjol:',
            hasCta: false,
          },
          {
            id: 'les_1_2',
            moduleId: 'mod_1',
            title: 'Sesi 2: Ciri-Ciri Anak Mesin Kecerdasan Sensing vs Thinking',
            order: 2,
            videoYoutubeUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
            videoExternalId: 'dQw4w9WgXcQ',
            textContent: 'Anak Sensing belajar lewat praktik dan memori konkrit, sedangkan anak Thinking belajar lewat skema logika.',
            hasReflection: true,
            reflectionType: 'long_text',
            reflectionPrompt: 'Apakah anak Anda lebih cenderung menghafal fakta atau mempertanyakan alasan?',
            hasCta: true,
            ctaLabel: 'Konsultasi Hasil Tes via WhatsApp',
            ctaUrl: 'https://wa.me/6281234567890?text=Saya%20ingin%20konsultasi%20tes%20STIFIn',
          },
        ],
      },
      {
        id: 'mod_2',
        programId: 'prog_7_hari_belajar',
        title: 'Modul 2: Pendampingan Tanpa Emosi',
        order: 2,
        lessons: [
          {
            id: 'les_2_1',
            moduleId: 'mod_2',
            title: 'Sesi 3: Mengatasi Kendala Konsentrasi Saat Belajar di Rumah',
            order: 1,
            videoYoutubeUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
            videoExternalId: 'dQw4w9WgXcQ',
            textContent: 'Kendala konsentrasi sering dialami jika media belajar tidak sesuai dengan gaya belajar anak.',
            hasReflection: true,
            reflectionType: 'long_text',
            reflectionPrompt: 'Apa tantangan terbesar saat mendampingi anak belajar menggunakan HP / gadget?',
            hasCta: false,
          },
        ],
      },
    ],
  },
  {
    id: 'prog_30_hari_setelah_tes',
    organizationId: SEED_ORGANIZATION.id,
    workspaceSlug: 'rina',
    programSlug: '30-hari-setelah-tes',
    title: '30 Hari Setelah Tes',
    subtitle: 'Panduan Pendampingan Setelah Tes Agar Hasil Tidak Berhenti Sebagai Laporan',
    description: 'Program pendampingan khusus bagi peserta yang telah menyelesaikan tes STIFIn untuk menerjemahkan hasil tes menjadi kebiasaan harian di rumah.',
    programType: 'aftersales',
    accessType: 'manual',
    status: 'published',
    pricing: 'free',
    priceAmount: 0,
    bankTransferEnabled: false,
    whatsAppEnabled: false,
    createdAt: '2026-08-02T00:00:00.000Z',
    updatedAt: '2026-08-02T00:00:00.000Z',
    modules: [
      {
        id: 'mod_aft_1',
        programId: 'prog_30_hari_setelah_tes',
        title: 'Modul 1: Membaca Laporan Hasil Tes',
        order: 1,
        lessons: [
          {
            id: 'les_aft_1_1',
            moduleId: 'mod_aft_1',
            title: 'Sesi 1: Memahami Mesin Kecerdasan & Drivren Dominan',
            order: 1,
            textContent: 'Penjelasan mendalam mengenai grafik hasil tes STIFIn.',
            hasReflection: true,
            reflectionType: 'long_text',
            reflectionPrompt: 'Apa poin terbesar dari laporan hasil tes yang membuat Anda paling terkesan?',
            hasCta: false,
          },
        ],
      },
    ],
  },
  {
    id: 'prog_parenting_growth',
    organizationId: SEED_ORGANIZATION.id,
    workspaceSlug: 'rina',
    programSlug: 'parenting-growth',
    title: 'Parenting Growth',
    subtitle: 'Pendampingan Lebih Mendalam untuk Membangun Pola Komunikasi Keluarga',
    description: 'Program pendampingan lanjutan 8 minggu untuk keluarga yang ingin membangun pola komunikasi harmonis dan bertumbuh bersama.',
    programType: 'paid',
    accessType: 'public',
    status: 'published',
    pricing: 'one_time',
    priceAmount: 450000,
    bankTransferEnabled: true,
    whatsAppEnabled: true,
    createdAt: '2026-08-03T00:00:00.000Z',
    updatedAt: '2026-08-03T00:00:00.000Z',
    modules: [
      {
        id: 'mod_pg_1',
        programId: 'prog_parenting_growth',
        title: 'Modul 1: Ekosistem Komunikasi Keluarga',
        order: 1,
        lessons: [
          {
            id: 'les_pg_1_1',
            moduleId: 'mod_pg_1',
            title: 'Sesi 1: Peta Komunikasi Pasangan & Anak',
            order: 1,
            textContent: 'Menganalisis dinamika komunikasi dalam keluarga.',
            hasReflection: true,
            reflectionType: 'long_text',
            reflectionPrompt: 'Tuliskan situasi komunikasi yang paling ingin Anda perbaiki:',
            hasCta: false,
          },
        ],
      },
    ],
  },
  {
    id: 'prog_private_mentoring',
    organizationId: SEED_ORGANIZATION.id,
    workspaceSlug: 'rina',
    programSlug: 'private-mentoring-keluarga',
    title: 'Private Mentoring Keluarga',
    subtitle: 'Mentoring Privat Eksklusif',
    description: 'Sesi mentoring privat tatap muka atau daring khusus 1-on-1.',
    programType: 'private',
    accessType: 'private',
    status: 'published',
    pricing: 'one_time',
    priceAmount: 1500000,
    bankTransferEnabled: true,
    whatsAppEnabled: true,
    createdAt: '2026-08-04T00:00:00.000Z',
    updatedAt: '2026-08-04T00:00:00.000Z',
    modules: [],
  },
  {
    id: 'prog_draft_concept',
    organizationId: SEED_ORGANIZATION.id,
    workspaceSlug: 'rina',
    programSlug: 'draft-konsep-baru',
    title: 'Draft Konsep Baru',
    subtitle: 'Program dalam Tahap Penyusunan',
    description: 'Draft materi baru yang belum siap dipublikasikan.',
    programType: 'lead_magnet',
    accessType: 'public',
    status: 'draft',
    pricing: 'free',
    priceAmount: 0,
    bankTransferEnabled: false,
    whatsAppEnabled: false,
    createdAt: '2026-08-05T00:00:00.000Z',
    updatedAt: '2026-08-05T00:00:00.000Z',
    modules: [],
  },
];

export const SEED_ENROLLMENTS: Enrollment[] = [
  {
    id: 'enr_ayu_7hari',
    organizationId: SEED_ORGANIZATION.id,
    contactId: 'contact_ayu',
    programId: 'prog_7_hari_belajar',
    status: 'aktif',
    enrolledAt: '2026-08-10T10:00:00.000Z',
    progressPercent: 33,
    completedLessonIds: ['les_1_1'],
    lessonProgress: {
      les_1_1: {
        completed: true,
        completedAt: '2026-08-10T10:30:00.000Z',
        reflectionAnswer: 'Anak saya sangat aktif dan suka belajar sambil bergerak konkrit.',
      },
    },
  },
  {
    id: 'enr_nina_7hari',
    organizationId: SEED_ORGANIZATION.id,
    contactId: 'contact_nina',
    programId: 'prog_7_hari_belajar',
    status: 'aktif',
    enrolledAt: '2026-08-11T14:00:00.000Z',
    progressPercent: 66,
    completedLessonIds: ['les_1_1', 'les_1_2'],
    lessonProgress: {
      les_1_1: {
        completed: true,
        completedAt: '2026-08-11T14:20:00.000Z',
        reflectionAnswer: 'Anak saya suka memvisualisasikan pelajaran.',
      },
      les_1_2: {
        completed: true,
        completedAt: '2026-08-11T14:45:00.000Z',
        reflectionAnswer: 'Anak saya sangat cenderung Thinking, selalu tanya kenapa.',
      },
    },
  },
];

export const SEED_REFLECTIONS: Reflection[] = [
  {
    id: 'refl_ayu_1',
    organizationId: SEED_ORGANIZATION.id,
    enrollmentId: 'enr_ayu_7hari',
    lessonId: 'les_1_1',
    contactId: 'contact_ayu',
    reflectionType: 'long_text',
    answerText: 'Anak saya sangat aktif dan suka belajar sambil bergerak konkrit.',
    submittedAt: '2026-08-10T10:30:00.000Z',
  },
  {
    id: 'refl_nina_1',
    organizationId: SEED_ORGANIZATION.id,
    enrollmentId: 'enr_nina_7hari',
    lessonId: 'les_1_1',
    contactId: 'contact_nina',
    reflectionType: 'long_text',
    answerText: 'Anak saya suka memvisualisasikan pelajaran.',
    submittedAt: '2026-08-11T14:20:00.000Z',
  },
];

export const SEED_LEARNING_EVENTS: LearningEvent[] = [
  {
    id: 'evt_ayu_reg',
    organizationId: SEED_ORGANIZATION.id,
    contactId: 'contact_ayu',
    eventType: 'learner.registered',
    programId: 'prog_7_hari_belajar',
    enrollmentId: 'enr_ayu_7hari',
    payload: {},
    occurredAt: '2026-08-10T10:00:00.000Z',
  },
  {
    id: 'evt_ayu_enr',
    organizationId: SEED_ORGANIZATION.id,
    contactId: 'contact_ayu',
    eventType: 'learner.enrolled',
    programId: 'prog_7_hari_belajar',
    enrollmentId: 'enr_ayu_7hari',
    payload: {},
    occurredAt: '2026-08-10T10:00:00.000Z',
  },
  {
    id: 'evt_ayu_les1_1',
    organizationId: SEED_ORGANIZATION.id,
    contactId: 'contact_ayu',
    eventType: 'lesson.completed',
    programId: 'prog_7_hari_belajar',
    enrollmentId: 'enr_ayu_7hari',
    lessonId: 'les_1_1',
    payload: {},
    occurredAt: '2026-08-10T10:30:00.000Z',
  },
  {
    id: 'evt_ayu_refl1_1',
    organizationId: SEED_ORGANIZATION.id,
    contactId: 'contact_ayu',
    eventType: 'reflection.submitted',
    programId: 'prog_7_hari_belajar',
    enrollmentId: 'enr_ayu_7hari',
    lessonId: 'les_1_1',
    payload: { answerText: 'Anak saya sangat aktif dan suka belajar sambil bergerak konkrit.' },
    occurredAt: '2026-08-10T10:30:00.000Z',
  },
  {
    id: 'evt_nina_reg',
    organizationId: SEED_ORGANIZATION.id,
    contactId: 'contact_nina',
    eventType: 'learner.registered',
    programId: 'prog_7_hari_belajar',
    enrollmentId: 'enr_nina_7hari',
    payload: {},
    occurredAt: '2026-08-11T14:00:00.000Z',
  },
  {
    id: 'evt_nina_enr',
    organizationId: SEED_ORGANIZATION.id,
    contactId: 'contact_nina',
    eventType: 'learner.enrolled',
    programId: 'prog_7_hari_belajar',
    enrollmentId: 'enr_nina_7hari',
    payload: {},
    occurredAt: '2026-08-11T14:00:00.000Z',
  },
  {
    id: 'evt_nina_les1_1',
    organizationId: SEED_ORGANIZATION.id,
    contactId: 'contact_nina',
    eventType: 'lesson.completed',
    programId: 'prog_7_hari_belajar',
    enrollmentId: 'enr_nina_7hari',
    lessonId: 'les_1_1',
    payload: {},
    occurredAt: '2026-08-11T14:20:00.000Z',
  },
  {
    id: 'evt_nina_prog50',
    organizationId: SEED_ORGANIZATION.id,
    contactId: 'contact_nina',
    eventType: 'program.progress_50',
    programId: 'prog_7_hari_belajar',
    enrollmentId: 'enr_nina_7hari',
    payload: { progressPercent: 66 },
    occurredAt: '2026-08-11T14:45:00.000Z',
  },
];

export const SEED_SIGNALS: LearningSignal[] = [
  {
    id: 'sig_ayu_7hari',
    organizationId: SEED_ORGANIZATION.id,
    contactId: 'contact_ayu',
    programId: 'prog_7_hari_belajar',
    enrollmentId: 'enr_ayu_7hari',
    sourceEventId: 'evt_ayu_les1_1',
    signalLevel: 'Minat sedang',
    intentScore: 20,
    primaryReason: 'Aktif menyelesaikan sesi pelajaran',
    rawReflectionQuote: 'Anak saya sangat aktif dan suka belajar sambil bergerak konkrit.',
    status: 'ACTIVE',
    evaluatedAt: '2026-08-10T10:30:00.000Z',
  },
  {
    id: 'sig_nina_7hari',
    organizationId: SEED_ORGANIZATION.id,
    contactId: 'contact_nina',
    programId: 'prog_7_hari_belajar',
    enrollmentId: 'enr_nina_7hari',
    sourceEventId: 'evt_nina_prog50',
    signalLevel: 'Minat tinggi',
    intentScore: 40,
    primaryReason: 'Mencapai progres 50%',
    rawReflectionQuote: 'Anak saya sangat cenderung Thinking, selalu tanya kenapa.',
    status: 'ACTIVE',
    evaluatedAt: '2026-08-11T14:45:00.000Z',
  },
];
