import {
  Contact,
  Program,
  Enrollment,
  Reflection,
  LearningSignal,
  LearningEvent,
} from '@promotor/contracts';

export const SEED_ORGANIZATION = {
  id: 'org_rina_stifin',
  name: 'Rina Parenting & STIFIn Center',
  slug: 'rina',
  createdAt: '2026-01-01T00:00:00Z',
};

export const SEED_CONTACTS: Contact[] = [
  {
    id: 'contact_ayu',
    organizationId: 'org_rina_stifin',
    name: 'Ayu Lestari',
    phoneE164: '+6281987654321',
    createdAt: '2026-08-01T10:00:00Z',
  },
  {
    id: 'contact_nina',
    organizationId: 'org_rina_stifin',
    name: 'Nina Rahmawati',
    phoneE164: '+6281876543210',
    createdAt: '2026-08-05T14:30:00Z',
  },
  {
    id: 'contact_budi',
    organizationId: 'org_rina_stifin',
    name: 'Budi Santoso',
    phoneE164: '+6281765432109',
    createdAt: '2026-08-08T09:15:00Z',
  },
];

export const SEED_PROGRAMS: Program[] = [
  {
    id: 'prog_7_hari_belajar',
    organizationId: 'org_rina_stifin',
    workspaceSlug: 'rina',
    programSlug: '7-hari-mengenal-cara-belajar-anak',
    title: '7 Hari Mengenal Cara Belajar Anak',
    subtitle: 'Panduan Praktis Orang Tua Mengidentifikasi Mesin Kecerdasan Anak',
    description: 'Program edukasi 7 hari untuk mengamati pola respon dan cara belajar terbaik anak di rumah.',
    programType: 'lead_magnet',
    accessType: 'public',
    status: 'published',
    pricing: 'free',
    createdAt: '2026-08-01T08:00:00Z',
    updatedAt: '2026-08-10T12:00:00Z',
    modules: [
      {
        id: 'mod_1',
        programId: 'prog_7_hari_belajar',
        title: 'Modul 1: Memahami Pola Respon Anak',
        order: 1,
        lessons: [
          {
            id: 'les_1_1',
            moduleId: 'mod_1',
            title: 'Hari 1: Mengamati Karakter Utama saat Belajar',
            order: 1,
            videoYoutubeUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
            videoExternalId: 'dQw4w9WgXcQ',
            textContent: 'Setiap anak memiliki cara unik dalam menerima informasi. Ada yang lebih cepat memahami lewat visual, pendengaran, maupun gerak fisik.',
            attachments: [
              {
                id: 'att_1',
                name: 'Lembar-kerja-pola-belajar.pdf',
                url: '/files/lembar-kerja.pdf',
                sizeFormatted: '1.2 MB',
              },
            ],
            hasReflection: true,
            reflectionType: 'long_text',
            reflectionPrompt: 'Tuliskan 1 hal yang paling menonjol saat anak Anda belajar hari ini:',
            hasCta: false,
          },
          {
            id: 'les_1_2',
            moduleId: 'mod_1',
            title: 'Hari 2: Menangani Konflik Penggunaan HP',
            order: 2,
            videoYoutubeUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
            videoExternalId: 'dQw4w9WgXcQ',
            textContent: 'Penggunaan gawai sering kali menjadi sumber ketegangan di rumah jika tidak dibarengi dengan kesepakatan batas waktu yang tepat.',
            hasReflection: true,
            reflectionType: 'long_text',
            reflectionPrompt: 'Apa kendala utama yang sering terjadi saat Anda mencoba membatasi waktu main HP anak?',
            hasCta: true,
            ctaLabel: 'Konsultasi Hasil via WhatsApp',
            ctaUrl: 'https://wa.me/6281234567890?text=Halo%20Mbak%20Rina,%20saya%20ingin%20konsultasi',
          },
        ],
      },
      {
        id: 'mod_2',
        programId: 'prog_7_hari_belajar',
        title: 'Modul 2: Rencana Tindakan Rumah',
        order: 2,
        lessons: [
          {
            id: 'les_2_1',
            moduleId: 'mod_2',
            title: 'Hari 3: Rencana Tindakan Pendampingan',
            order: 1,
            textContent: 'Merumuskan 3 aturan sederhana untuk menemani anak belajar tanpa kemarahan.',
            hasReflection: true,
            reflectionType: 'long_text',
            reflectionPrompt: 'Tuliskan 3 komitmen belajar bersama anak minggu ini:',
            hasCta: true,
            ctaLabel: 'Jadwalkan Tes STIFIn Anak',
            ctaUrl: 'https://wa.me/6281234567890?text=Halo%20Mbak%20Rina,%20saya%20mau%20booking%20Tes%20STIFIn',
          },
        ],
      },
    ],
  },
];

export const SEED_ENROLLMENTS: Enrollment[] = [
  {
    id: 'enr_ayu_7hari',
    organizationId: 'org_rina_stifin',
    contactId: 'contact_ayu',
    programId: 'prog_7_hari_belajar',
    status: 'selesai',
    enrolledAt: '2026-08-02T09:00:00Z',
    completedAt: '2026-08-12T10:00:00Z',
    progressPercent: 100,
    completedLessonIds: ['les_1_1', 'les_1_2', 'les_2_1'],
    lessonProgress: {
      les_1_1: { completed: true, completedAt: '2026-08-02T10:00:00Z', reflectionAnswer: 'Anak saya sangat aktif dan mudah bosan kalau hanya diminta membaca teks.' },
      les_1_2: { completed: true, completedAt: '2026-08-05T11:00:00Z', reflectionAnswer: 'Kalau sudah main HP susah berhenti dan sering mengamuk.' },
      les_2_1: { completed: true, completedAt: '2026-08-12T10:00:00Z', reflectionAnswer: 'Saya berkomitmen membatasi HP 1 jam per hari dan rutin mendampingi belajar jam 7 malam.' },
    },
  },
  {
    id: 'enr_nina_7hari',
    organizationId: 'org_rina_stifin',
    contactId: 'contact_nina',
    programId: 'prog_7_hari_belajar',
    status: 'aktif',
    enrolledAt: '2026-08-06T14:00:00Z',
    progressPercent: 66,
    completedLessonIds: ['les_1_1', 'les_1_2'],
    lessonProgress: {
      les_1_1: { completed: true, completedAt: '2026-08-06T15:00:00Z', reflectionAnswer: 'Anak saya lebih suka mendengarkan cerita daripada membaca buku sendiri.' },
      les_1_2: { completed: true, completedAt: '2026-08-12T08:30:00Z', reflectionAnswer: 'Penggunaan HP sering memicu konflik saat jam belajar.' },
    },
  },
];

export const SEED_REFLECTIONS: Reflection[] = [
  {
    id: 'refl_ayu_1',
    organizationId: 'org_rina_stifin',
    enrollmentId: 'enr_ayu_7hari',
    lessonId: 'les_2_1',
    contactId: 'contact_ayu',
    reflectionType: 'long_text',
    answerText: 'Saya berkomitmen membatasi HP 1 jam per hari dan rutin mendampingi belajar jam 7 malam.',
    submittedAt: '2026-08-12T10:00:00Z',
  },
  {
    id: 'refl_nina_1',
    organizationId: 'org_rina_stifin',
    enrollmentId: 'enr_nina_7hari',
    lessonId: 'les_1_2',
    contactId: 'contact_nina',
    reflectionType: 'long_text',
    answerText: 'Penggunaan HP sering memicu konflik saat jam belajar.',
    submittedAt: '2026-08-12T08:30:00Z',
  },
];

export const SEED_LEARNING_EVENTS: LearningEvent[] = [
  {
    id: 'evt_ayu_enrolled',
    organizationId: 'org_rina_stifin',
    contactId: 'contact_ayu',
    eventType: 'learner.enrolled',
    programId: 'prog_7_hari_belajar',
    enrollmentId: 'enr_ayu_7hari',
    payload: {},
    occurredAt: '2026-08-02T09:00:00Z',
  },
  {
    id: 'evt_ayu_les1_1',
    organizationId: 'org_rina_stifin',
    contactId: 'contact_ayu',
    eventType: 'lesson.completed',
    programId: 'prog_7_hari_belajar',
    enrollmentId: 'enr_ayu_7hari',
    lessonId: 'les_1_1',
    payload: {},
    occurredAt: '2026-08-02T10:00:00Z',
  },
  {
    id: 'evt_ayu_prog_50',
    organizationId: 'org_rina_stifin',
    contactId: 'contact_ayu',
    eventType: 'program.progress_50',
    programId: 'prog_7_hari_belajar',
    enrollmentId: 'enr_ayu_7hari',
    payload: { progressPercent: 66 },
    occurredAt: '2026-08-05T11:00:00Z',
  },
  {
    id: 'evt_ayu_prog_80',
    organizationId: 'org_rina_stifin',
    contactId: 'contact_ayu',
    eventType: 'program.progress_80',
    programId: 'prog_7_hari_belajar',
    enrollmentId: 'enr_ayu_7hari',
    payload: { progressPercent: 100 },
    occurredAt: '2026-08-12T10:00:00Z',
  },
  {
    id: 'evt_ayu_prog_completed',
    organizationId: 'org_rina_stifin',
    contactId: 'contact_ayu',
    eventType: 'program.completed',
    programId: 'prog_7_hari_belajar',
    enrollmentId: 'enr_ayu_7hari',
    payload: { progressPercent: 100 },
    occurredAt: '2026-08-12T10:00:00Z',
  },
  {
    id: 'evt_nina_enrolled',
    organizationId: 'org_rina_stifin',
    contactId: 'contact_nina',
    eventType: 'learner.enrolled',
    programId: 'prog_7_hari_belajar',
    enrollmentId: 'enr_nina_7hari',
    payload: {},
    occurredAt: '2026-08-06T14:00:00Z',
  },
  {
    id: 'evt_nina_les1_1',
    organizationId: 'org_rina_stifin',
    contactId: 'contact_nina',
    eventType: 'lesson.completed',
    programId: 'prog_7_hari_belajar',
    enrollmentId: 'enr_nina_7hari',
    lessonId: 'les_1_1',
    payload: {},
    occurredAt: '2026-08-06T15:00:00Z',
  },
  {
    id: 'evt_nina_prog_50',
    organizationId: 'org_rina_stifin',
    contactId: 'contact_nina',
    eventType: 'program.progress_50',
    programId: 'prog_7_hari_belajar',
    enrollmentId: 'enr_nina_7hari',
    payload: { progressPercent: 66 },
    occurredAt: '2026-08-12T08:30:00Z',
  },
];

export const SEED_SIGNALS: LearningSignal[] = [
  {
    id: 'sig_ayu_completed',
    organizationId: 'org_rina_stifin',
    contactId: 'contact_ayu',
    enrollmentId: 'enr_ayu_7hari',
    signalLevel: 'Minat tinggi',
    intentScore: 70, // 10 (enrolled) + 10 (1st lesson) + 20 (progress_50) + 20 (progress_80) + 20 (completed) - no CTA click yet = 80
    primaryReason: 'Program selesai',
    rawReflectionQuote: 'Saya berkomitmen membatasi HP 1 jam per hari...',
    status: 'ACTIVE',
    evaluatedAt: '2026-08-12T10:00:00Z',
  },
  {
    id: 'sig_nina_hp_conflict',
    organizationId: 'org_rina_stifin',
    contactId: 'contact_nina',
    enrollmentId: 'enr_nina_7hari',
    signalLevel: 'Minat sedang',
    intentScore: 40, // 10 (enrolled) + 10 (1st lesson) + 20 (progress_50) = 40
    primaryReason: 'Refleksi menyebut konflik penggunaan HP',
    rawReflectionQuote: 'Penggunaan HP sering memicu konflik...',
    status: 'ACTIVE',
    evaluatedAt: '2026-08-12T08:30:00Z',
  },
];
